Fix C++20 global module fragment inclusion
skypjack/entt pull request #1047
Opened 2023-07-31 17:25 UTC by DonutVikingChap

Using the experimental C++20 modules support in recent builds of Clang, EnTT currently causes compilation errors when included as part of the global module fragment in a module interface unit that exports part of EnTT's API and is then imported and used by a different translation unit. Here is a minimal example (note the "error: no matching function for call to 'popcount'" in the output): https://godbolt.org/z/3dozc9z4h

The reason seems to be that certain function declarations that are implicitly required by the implementation aren't exported into the module interface since they are erroneously marked 'static' and have internal linkage when they should (presumably) be 'inline'. I found that changing these declarations accordingly fixed the problem and made EnTT work well with C++20 modules in my project, and this PR reflects those changes.

Unfortunately I can't write proper test cases for this since it depends on features that are still experimental in most compilers, so there may still be other static declarations that I have missed that could cause problems in other modules-based projects, but as long as these changes don't break anything for regular non-modules builds, they should hopefully at least help make EnTT a bit more modules-friendly in the short term.

2023-08-01 07:13 UTC, skypjack commented
Makes sense actually, thanks for pointing this out. Why `inline` though? We can just drop the `static` and that's it.
Those are template functions, no need to make them inline to avoid symbols duplication. On the other hand, I'm pretty sure that the compiler knows better than me whether to inline them or not.
So, yeah, I'd rather get rid of it if possible before merging. Thanks. 👍

2023-08-01 07:14 UTC, skypjack requested changes

2023-08-01 07:14 UTC, skypjack commented on src/entt/core/type_info.hpp
> +[[nodiscard]] inline std::string_view type_name(char) noexcept {
No need to make this one `inline`.

2023-08-01 07:14 UTC, skypjack commented on src/entt/core/type_info.hpp
> +[[nodiscard]] inline id_type type_hash(char) noexcept {
No need to make this one `inline`.

2023-08-01 15:21 UTC, DonutVikingChap commented
Ok, the inline specifiers are removed now. In my own projects I usually mark all header-defined free functions either inline or constexpr even when they're templates. It's mostly for consistency, but also to make sure that the inline specifier is not accidentally forgotten in case the function is later refactored to not be a template, though I agree that it's not strictly necessary here.

2023-08-02 12:17 UTC, skypjack commented
Yeah, don't get me wrong. What you say makes perfectly sense. I'm just trying to stick with the coding style of this project. 👍 
Thanks for changing it. Let me know if you spot any other changes that are useful to make it work with C++20.
I also want to create a C++20 branch of the library soon, most likely after the vacations. 🥳

2023-08-02 12:18 UTC, skypjack approved these changes

2023-08-02 12:19 UTC, merged