Add organizer dependencies
skypjack/entt pull request #1069
Opened 2023-09-18 14:24 UTC by cjhowedev

Adds the indices of the in edges of organizer vertices, so that dependencies can be checked for completion before running a vertex's task. Also simplifies how the `is_top_level` field is calculated to reuse the passed in dependencies.

2023-09-18 18:03 UTC, cjhowedev commented
Yes, I can rename it if that helps clarify.

2023-09-19 08:35 UTC, skypjack commented
Well, I don't like `parent` either but I'd change the name to _<let's find the right one>_.
The fact is that _dependencies_ makes me think to something on which the node depends rather than something that depends on the node, if you get what I mean.

2023-09-19 08:43 UTC, Innokentiy-Alaytsev commented
1. Dependent
2. Successor
3. Derivative
4. Subject (?)

2023-09-19 14:01 UTC, cjhowedev commented
Hmm, if we don't use the terminology `parent`, I don't think we should use `children` either. I think the best path forward is to rename both to `successors`/`predecessors` to reduce confusion as to where they are in the graph.

2023-09-19 14:07 UTC, skypjack commented
Approved. 👍

2023-09-19 14:31 UTC, cjhowedev commented
Updated the commit message to match others. I also decided to keep `children` around for backwards compatibility, and have created `successors`/`predecessors`. The code should be ready for review.

2023-09-21 06:42 UTC, skypjack requested changes

2023-09-21 06:42 UTC, skypjack commented on src/entt/entity/organizer.hpp
> +         * @param edges The indices of the dependencies in the adjacency list.
`edges` -> `predecessors`?

2023-09-21 06:42 UTC, skypjack commented on src/entt/entity/organizer.hpp
>           * @param vtype True if the vertex is a top-level one, false otherwise.
`vtype` should go away, isn't it?

2023-09-21 06:42 UTC, skypjack commented on src/entt/entity/organizer.hpp
>          const std::vector<std::size_t> &children() const noexcept {
Keep this one here is fine but I'd add a `[[deprecated("use ::successors")]]` too.

2023-09-21 06:42 UTC, skypjack commented on test/entt/entity/organizer.cpp
> -    ASSERT_EQ(graph[0u].children().size(), 2u);
Since `children` still exists, please, do not drop its tests or the coverage tool will complain. 👍

2023-10-13 16:07 UTC, skypjack commented on test/entt/entity/organizer.cpp
> -    ASSERT_EQ(graph[0u].children().size(), 2u);
Ping @cjhowedev 🙂

2024-05-06 11:42 UTC, skypjack commented
Available on `wip`, updated to the latest version of the library.

2024-05-06 11:42 UTC, closed without merging